[project]
  name            = "gigarandr"
  version         = "0.4.2"
  description     = "Add your description here"
  readme          = "README.md"
  requires-python = ">=3.12"

  dependencies = ["loguru>=0.7.3", "omegaconf>=2.3.0", "typer>=0.15.1"]

  [project.scripts]
    gigarandr = "gigarandr:main"


[tool.uv]
  dev-dependencies = [
    "hypothesis>=6.125.3",
    "pytest-cov>=6.0.0",
    "pytest>=8.3.4",
  ]
